# API ci
variables:
  SERVICE_NAME: "api"
 
deploy:
  stage: deploy
  only:
    - production

  image: google/cloud-sdk:latest
  script:
    - echo $GCP_SERVICE_ACCOUNT_PROD > gcloud-service-key.json 
    - gcloud auth activate-service-account --key-file gcloud-service-key.json 
    - gcloud auth configure-docker 
    - gcloud config set project $GCP_PROJECT_ID_PROD
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID_PROD/$SERVICE_NAME 
    - gcloud run deploy $SERVICE_NAME --image gcr.io/$GCP_PROJECT_ID_PROD/$SERVICE_NAME --region=us-central1 --platform managed --allow-unauthenticated 