FROM node

WORKDIR /app

COPY package*.json ./
RUN yarn

COPY . .

RUN echo 'APP_ENV=production' >> .env
RUN echo 'APP_PORT=9000' >> .env
RUN echo 'FRESHSALES_API_KEY="fPjGQStTY1ffGqtyAj9RVw"' >> .env
RUN echo 'FRESHSALES_BASE_URL="https://railflow.myfreshworks.com"' >> .env
RUN echo 'ALLOWED_DOMAINS=["http://localhost:8000", "http://localhost","http://localhost:9000", "https://railflow.io"]' >> .env
RUN echo 'CRYPTOLENS_BASE_URL="https://app.cryptolens.io"' >> .env
RUN echo 'CRYPTOLENS_API_KEY="WyI0NDk1MzMiLCJqdjFYRGJYc0RuVmFHU0NmdFlnUWptMklTcXdVai9lNVRnRklkL3Y3Il0="' >> .env
RUN echo 'MAILGUN_KEY="key-4c45b28d4cab5d63a74df82c99aae76c"' >> .env
RUN echo 'HIVEAGE_DOMAIN="railflow"' >> .env
RUN echo 'HIVEAGE_BASE_URL="https://railflow.hiveage.com/"' >> .env
RUN echo 'HIVEAGE_API_KEY="ByVEuVLBWbch9B5Ejnsq"' >> .env
RUN echo 'SLACK_API_BASE_URL="https://hooks.slack.com/services/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"' >> .env
RUN echo 'SLACK_SLASH_COMMAND_TOKEN: "kBWbldLF6g11eDX5rpyRQUY4"' >> .env
RUN echo 'CRYPTOLENS_LICENSE_EXTENSION_KEY="WyIyODk0MTIiLCIwQUx0TG1LRWxUNXZRZXJLYWJMZzBUY3NLSGJ0akgvaCtkZEx4b3h6Il0="' >> .env
RUN echo 'CRYPTOLENS_RSA_PUB_KEY="<RSAKeyValue><Modulus>5TFzvx1Ygenf7BJYxliBFkcKSDebrxVTUteai/xjHP/Tmrx2z5h5vJRkQlg6vxecbLDj7g+TAvZssEVj5D1VVtur2Od1Fdqs49m0dA+QdGBv5DXt9YeqJLW/JpciMom79HcOeIvJDTHJcQssCXKLxGnQkTpMIpB22hTOuJTcj1bmLManR6mQYX2k/BZ/XkC2l61TbKaOnKww3BrX8+b2ImT89VeN0znxIEwBUla78C6pDJTkKDPZPeHItHk9gTBx9CkCCfMdzidVxwiMFvXM7PSBWSFKn2JPO5+gawJbV+0nH95890EL80dl/OH/K5O+CYTaHrKJ+zUcY7MxLqsmCw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>"' >> .env
RUN echo 'AWS_ACCESS_KEY_ID="AKIA22332JGRSQN5TNMD"' >> .env
RUN echo 'AWS_SECRET_ACCESS_KEY="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"' >> .env
RUN echo 'ALLOWED_PARTY_SECRET=ALL' >> .env

EXPOSE 9000

CMD ["yarn", "start", "--", "-a", "0.0.0.0"]
